package com.critmx.improveditempickups.common.config;

public enum AnimationEase {
    LINEAR,
    IN_BACK, IN_BOUNCE, IN_CUBIC, IN_ELASTIC, IN_EXPO, IN_QUAD, IN_QUART, IN_QUINT, IN_SINE,
    IN_OUT_BACK, IN_OUT_BOUNCE, IN_OUT_CIRC, IN_OUT_CUBIC, IN_OUT_ELASTIC, IN_OUT_EXPO, IN_OUT_QUAD, IN_OUT_QUART, IN_OUT_QUINT, IN_OUT_SINE,
    OUT_BACK, OUT_BOUNCE, OUT_CUBIC, OUT_ELASTIC, OUT_EXPO, OUT_QUAD, OUT_QUART, OUT_QUINT, OUT_SINE,
    OUT_CIRC, IN_CIRC
}
